### ISSUE TITLE
Great Example - PR into tide example sections?

### ISSUE THREAD

**Issue by No9** [zzy/tide-async-graphql-mongodb#1]
Hey this is a very interesting example. Have you thought about adding it to the example applications list in tide? 
https://github.com/http-rs/tide#example-applications

**Comment by zzy** [comment]
> 
> 
> Hey this is a very interesting example. Have you thought about adding it to the example applications list in tide?
> https://github.com/http-rs/tide#example-applications

Hi, @No9, I have created PR #809.
Good day. :-)

**Comment by No9** [comment]
Thanks I saw this landed so I am closing
