### ISSUE TITLE
可以讲一下怎么引入谷歌第三方登录吗？

### ISSUE THREAD

**Issue by zwl1619** [zzy/tide-async-graphql-mongodb#3]
可以讲一下怎么引入谷歌第三方登录吗？

**Comment by zzy** [comment]
> 可以讲一下怎么引入谷歌第三方登录吗？

朋友好！
我应用中是在 frontend-handlebars 或者 frontend-yew 中集成，涉及很小部分的 tide 路由代码。通过 ajax 获取第三方的 token 的方式。
如果 token 通过数据库存取，在 graphql 服务中作为普通字符串处理即可。

**Comment by zwl1619** [comment]
谢谢！
